# Start ChromaDB and MongoDB latest versions

version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_DB: jobmatcher
    volumes:
      - mongo_data:/data/db

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma_data:/chroma/.chroma/index

volumes:
  mongo_data:
  chroma_data:

